# Import library

In [1]:
import argparse
import logging
import math
import os
import random
import time
from copy import deepcopy
from pathlib import Path
from threading import Thread

import numpy as np
import torch
import torch.distributed as dist
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.optim.lr_scheduler as lr_scheduler
import torch.utils.data
import yaml
from torch.cuda import amp
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.utils.tensorboard import SummaryWriter
from tqdm import tqdm

import test  # import test.py to get mAP after each epoch
from models.experimental import attempt_load
from models.yolo import Model
from utils.autoanchor import check_anchors
from utils.datasets import create_dataloader
from utils.general import labels_to_class_weights, increment_path, labels_to_image_weights, init_seeds, \
    fitness, strip_optimizer, get_latest_run, check_dataset, check_file, check_git_status, check_img_size, \
    check_requirements, print_mutation, set_logging, one_cycle, colorstr
from utils.google_utils import attempt_download
from utils.loss import ComputeLoss, ComputeLossAuxOTA
from utils.plots import plot_images, plot_labels, plot_results, plot_evolution
from utils.torch_utils import ModelEMA, select_device, intersect_dicts, torch_distributed_zero_first, is_parallel
from utils.wandb_logging.wandb_utils import WandbLogger, check_wandb_resume

logger = logging.getLogger(__name__)

from huggingface_hub import HfApi

# Get argument

In [2]:
parser = argparse.ArgumentParser()
parser.add_argument('--weights', type=str, default='last.pt', help='initial weights path')
parser.add_argument('--cfg', type=str, default='cfg/training/image_tagging_training.yaml', help='model.yaml path')
parser.add_argument('--data', type=str, default='data/image_tagging_data.yaml', help='data.yaml path')
parser.add_argument('--hyp', type=str, default='data/hyp.scratch.custom.yaml', help='hyperparameters path')
parser.add_argument('--epochs', type=int, default=10)
parser.add_argument('--batch-size', type=int, default=1, help='total batch size for all GPUs')
parser.add_argument('--img-size', nargs='+', type=int, default=[1280, 1280], help='[train, test] image sizes')
parser.add_argument('--rect', action='store_true', help='rectangular training')
parser.add_argument('--resume', nargs='?', const=True, default=False, help='resume most recent training')
parser.add_argument('--nosave', action='store_true', help='only save final checkpoint')
parser.add_argument('--notest', action='store_true', help='only test final epoch')
parser.add_argument('--noautoanchor', action='store_true', help='disable autoanchor check')
parser.add_argument('--evolve', action='store_true', help='evolve hyperparameters')
parser.add_argument('--bucket', type=str, default='', help='gsutil bucket')
parser.add_argument('--cache-images', action='store_true', help='cache images for faster training')
parser.add_argument('--image-weights', action='store_true', help='use weighted image selection for training')
parser.add_argument('--device', default='0', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
parser.add_argument('--multi-scale', action='store_true', help='vary img-size +/- 50%%')
parser.add_argument('--single-cls', action='store_true', help='train multi-class data as single-class')
parser.add_argument('--adam', action='store_true', help='use torch.optim.Adam() optimizer')
parser.add_argument('--sync-bn', action='store_true', help='use SyncBatchNorm, only available in DDP mode')
parser.add_argument('--local_rank', type=int, default=-1, help='DDP parameter, do not modify')
parser.add_argument('--workers', type=int, default=8, help='maximum number of dataloader workers')
parser.add_argument('--project', default='runs/train', help='save to project/name')
parser.add_argument('--entity', default=None, help='W&B entity')
parser.add_argument('--name', default='exp', help='save to project/name')
parser.add_argument('--exist-ok', action='store_true', help='existing project/name ok, do not increment')
parser.add_argument('--quad', action='store_true', help='quad dataloader')
parser.add_argument('--linear-lr', action='store_true', help='linear LR')
parser.add_argument('--label-smoothing', type=float, default=0.0, help='Label smoothing epsilon')
parser.add_argument('--upload_dataset', action='store_true', help='Upload dataset as W&B artifact table')
parser.add_argument('--bbox_interval', type=int, default=-1, help='Set bounding-box image logging interval for W&B')
parser.add_argument('--save_period', type=int, default=-1, help='Log model after every "save_period" epoch')
parser.add_argument('--artifact_alias', type=str, default="latest", help='version of dataset artifact to be used')
parser.add_argument('--v5-metric', action='store_true', help='assume maximum recall as 1.0 in AP calculation')

# to fix bug
parser.add_argument(
            "-i", "--ip", help="a dummy argument to fool ipython", default="1")
parser.add_argument(
    "-s", "--stdin", help="a dummy argument to fool ipython", default="1")
parser.add_argument(
    "-c", "--control", help="a dummy argument to fool ipython", default="1")
parser.add_argument(
    "-b", "--hb", help="a dummy argument to fool ipython", default="1")
parser.add_argument(
    "-K", "--Session.key", help="a dummy argument to fool ipython", default="1")
parser.add_argument(
    "-S", "--Session.signature_scheme", help="a dummy argument to fool ipython", default="1")
parser.add_argument(
    "-l", "--shell", help="a dummy argument to fool ipython", default="1")
parser.add_argument(
    "-t", "--transport", help="a dummy argument to fool ipython", default="1")
parser.add_argument(
    "-o", "--iopub", help="a dummy argument to fool ipython", default="1")
parser.add_argument('--f', default = 'runtime_ipynb.json')

opt = parser.parse_args()

# Set DDP variables
opt.world_size = int(os.environ['WORLD_SIZE']) if 'WORLD_SIZE' in os.environ else 1
opt.global_rank = int(os.environ['RANK']) if 'RANK' in os.environ else -1
set_logging(opt.global_rank)
#if opt.global_rank in [-1, 0]:
#    check_git_status()
#    check_requirements()

opt.exist_ok = True

# some preprocess

In [3]:
wandb_run = check_wandb_resume(opt)
if opt.resume and not wandb_run:  # resume an interrupted run
    ckpt = opt.resume if isinstance(opt.resume, str) else get_latest_run()  # specified or most recent path
    assert os.path.isfile(ckpt), 'ERROR: --resume checkpoint does not exist'
    apriori = opt.global_rank, opt.local_rank
    with open(Path(ckpt).parent.parent / 'opt.yaml') as f:
        opt = argparse.Namespace(**yaml.load(f, Loader=yaml.SafeLoader))  # replace
    opt.cfg, opt.weights, opt.resume, opt.batch_size, opt.global_rank, opt.local_rank = '', ckpt, True, opt.total_batch_size, *apriori  # reinstate
    logger.info('Resuming training from %s' % ckpt)
else:
    # opt.hyp = opt.hyp or ('hyp.finetune.yaml' if opt.weights else 'hyp.scratch.yaml')
    opt.data, opt.cfg, opt.hyp = check_file(opt.data), check_file(opt.cfg), check_file(opt.hyp)  # check files
    assert len(opt.cfg) or len(opt.weights), 'either --cfg or --weights must be specified'
    opt.img_size.extend([opt.img_size[-1]] * (2 - len(opt.img_size)))  # extend to 2 sizes (train, test)
    opt.name = 'evolve' if opt.evolve else opt.name
    opt.save_dir = increment_path(Path(opt.project) / opt.name, exist_ok=opt.exist_ok | opt.evolve)  # increment run

In [4]:
# DDP mode
opt.total_batch_size = opt.batch_size
device = select_device(opt.device, batch_size=opt.batch_size)
if opt.local_rank != -1:
    assert torch.cuda.device_count() > opt.local_rank
    torch.cuda.set_device(opt.local_rank)
    device = torch.device('cuda', opt.local_rank)
    dist.init_process_group(backend='nccl', init_method='env://')  # distributed backend
    assert opt.batch_size % opt.world_size == 0, '--batch-size must be multiple of CUDA device count'
    opt.batch_size = opt.total_batch_size // opt.world_size


YOLOR 🚀 2023-5-8 torch 1.10.0+cu111 CUDA:0 (NVIDIA GeForce GTX 1650, 3912.0MB)



In [5]:
# Hyperparameters
with open(opt.hyp) as f:
    hyp = yaml.load(f, Loader=yaml.SafeLoader)  # load hyps

In [6]:
# Train
logger.info(opt)
if not opt.evolve:
    tb_writer = None  # init loggers
    if opt.global_rank in [-1, 0]:
        prefix = colorstr('tensorboard: ')
        logger.info(f"{prefix}Start with 'tensorboard --logdir {opt.project}', view at http://localhost:6006/")
        tb_writer = SummaryWriter(opt.save_dir)  # Tensorboard
    # train(hyp, opt, device, tb_writer)

Namespace(weights='last.pt', cfg='cfg/training/image_tagging_training.yaml', data='data/image_tagging_data.yaml', hyp='data/hyp.scratch.custom.yaml', epochs=10, batch_size=1, img_size=[1280, 1280], rect=False, resume=False, nosave=False, notest=False, noautoanchor=False, evolve=False, bucket='', cache_images=False, image_weights=False, device='0', multi_scale=False, single_cls=False, adam=False, sync_bn=False, local_rank=-1, workers=8, project='runs/train', entity=None, name='exp', exist_ok=True, quad=False, linear_lr=False, label_smoothing=0.0, upload_dataset=False, bbox_interval=-1, save_period=-1, artifact_alias='latest', v5_metric=False, ip='127.0.0.1', stdin='9008', control='9006', hb='9005', shell='9007', transport='"tcp"', iopub='9009', f='/home/tavandai/.local/share/jupyter/runtime/kernel-v2-6775rJJEBNGirha9.json', world_size=1, global_rank=-1, save_dir='runs/train/exp', total_batch_size=1, **{'Session.key': 'b"a2e21488-7b30-4232-bc85-12e6bd522a74"', 'Session.signature_scheme':

# Explore train function

In [7]:
api = HfApi()

logger.info(colorstr('hyperparameters: ') + ', '.join(f'{k}={v}' for k, v in hyp.items()))
save_dir, epochs, batch_size, total_batch_size, weights, rank = \
    Path(opt.save_dir), opt.epochs, opt.batch_size, opt.total_batch_size, opt.weights, opt.global_rank


hyperparameters: lr0=0.01, lrf=0.1, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.3, cls_pw=1.0, obj=0.7, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.2, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, paste_in=0.0, loss_ota=1


In [8]:
# Directories
wdir = save_dir / 'weights'
wdir.mkdir(parents=True, exist_ok=True)  # make dir
last = wdir / 'last.pt'
best = wdir / 'best.pt'
results_file = save_dir / 'results.txt'

In [9]:
with open(save_dir / 'hyp.yaml', 'w') as f:
    yaml.dump(hyp, f, sort_keys=False)
with open(save_dir / 'opt.yaml', 'w') as f:
    yaml.dump(vars(opt), f, sort_keys=False)


In [10]:
# Configure
plots = not opt.evolve  # create plots
cuda = device.type != 'cpu'
init_seeds(2 + rank)
with open(opt.data) as f:
    data_dict = yaml.load(f, Loader=yaml.SafeLoader)  # data dict
is_coco = opt.data.endswith('coco.yaml')

# Logging- Doing this before checking the dataset. Might update data_dict
loggers = {'wandb': None}  # loggers dict
if rank in [-1, 0]:
    opt.hyp = hyp  # add hyperparameters
    run_id = torch.load(weights).get('wandb_id') if weights.endswith('.pt') and os.path.isfile(weights) else None
    wandb_logger = WandbLogger(opt, Path(opt.save_dir).stem, run_id, data_dict)
    loggers['wandb'] = wandb_logger.wandb
    data_dict = wandb_logger.data_dict
    if wandb_logger.wandb:
        weights, epochs, hyp = opt.weights, opt.epochs, opt.hyp  # WandbLogger might update weights, epochs if resuming

nc = 1 if opt.single_cls else int(data_dict['nc'])  # number of classes
names = ['item'] if opt.single_cls and len(data_dict['names']) != 1 else data_dict['names']  # class names
assert len(names) == nc, '%g names found for nc=%g dataset in %s' % (len(names), nc, opt.data)  # check


wandb: Install Weights & Biases for YOLOR logging with 'pip install wandb' (recommended)


# Load model

In [11]:
pretrained = weights.endswith('.pt')
if pretrained:
    with torch_distributed_zero_first(rank):
        attempt_download(weights)  # download if not found locally
    ckpt = torch.load(weights, map_location=device)  # load checkpoint
    model = Model(opt.cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
    exclude = ['anchor'] if (opt.cfg or hyp.get('anchors')) and not opt.resume else []  # exclude keys
    state_dict = ckpt['model'].float().state_dict()  # to FP32
    state_dict = intersect_dicts(state_dict, model.state_dict(), exclude=exclude)  # intersect
    model.load_state_dict(state_dict, strict=False)  # load
    logger.info('Transferred %g/%g items from %s' % (len(state_dict), len(model.state_dict()), weights))  # report
else:
    model = Model(opt.cfg, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create


                 from  n    params  module                                  arguments                     
  0                -1  1         0  models.common.ReOrg                     []                            
  1                -1  1      7040  models.common.Conv                      [12, 64, 3, 1]                
  2                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  3                -1  1      8320  models.common.Conv                      [128, 64, 1, 1]               
  4                -2  1      8320  models.common.Conv                      [128, 64, 1, 1]               
  5                -1  1     36992  models.common.Conv                      [64, 64, 3, 1]                
  6                -1  1     36992  models.common.Conv                      [64, 64, 3, 1]                
  7                -1  1     36992  models.common.Conv                      [64, 64, 3, 1]                
  8                -1  1     36992  

In [12]:
model.model[-1]

IAuxDetect(
  (m): ModuleList(
    (0): Conv2d(256, 153, kernel_size=(1, 1), stride=(1, 1))
    (1): Conv2d(512, 153, kernel_size=(1, 1), stride=(1, 1))
    (2): Conv2d(768, 153, kernel_size=(1, 1), stride=(1, 1))
    (3): Conv2d(1024, 153, kernel_size=(1, 1), stride=(1, 1))
  )
  (m2): ModuleList(
    (0): Conv2d(320, 153, kernel_size=(1, 1), stride=(1, 1))
    (1): Conv2d(640, 153, kernel_size=(1, 1), stride=(1, 1))
    (2): Conv2d(960, 153, kernel_size=(1, 1), stride=(1, 1))
    (3): Conv2d(1280, 153, kernel_size=(1, 1), stride=(1, 1))
  )
  (ia): ModuleList(
    (0): ImplicitA()
    (1): ImplicitA()
    (2): ImplicitA()
    (3): ImplicitA()
  )
  (im): ModuleList(
    (0): ImplicitM()
    (1): ImplicitM()
    (2): ImplicitM()
    (3): ImplicitM()
  )
)

# Load dataset

In [13]:
with torch_distributed_zero_first(rank):
    check_dataset(data_dict)  # check
train_path = data_dict['train']
test_path = data_dict['val']

In [14]:
train_path

'custom_data/images/train'

# Some option for model

In [13]:
# Freeze
freeze = []  # parameter names to freeze (full or partial)
for k, v in model.named_parameters():
    v.requires_grad = True  # train all layers
    if any(x in k for x in freeze):
        print('freezing %s' % k)
        v.requires_grad = False


In [14]:
# Optimizer
nbs = 64  # nominal batch size
accumulate = max(round(nbs / total_batch_size), 1)  # accumulate loss before optimizing
hyp['weight_decay'] *= total_batch_size * accumulate / nbs  # scale weight_decay
logger.info(f"Scaled weight_decay = {hyp['weight_decay']}")

pg0, pg1, pg2 = [], [], []  # optimizer parameter groups
for k, v in model.named_modules():
    if hasattr(v, 'bias') and isinstance(v.bias, nn.Parameter):
        pg2.append(v.bias)  # biases
    if isinstance(v, nn.BatchNorm2d):
        pg0.append(v.weight)  # no decay
    elif hasattr(v, 'weight') and isinstance(v.weight, nn.Parameter):
        pg1.append(v.weight)  # apply decay
    if hasattr(v, 'im'):
        if hasattr(v.im, 'implicit'):           
            pg0.append(v.im.implicit)
        else:
            for iv in v.im:
                pg0.append(iv.implicit)
    if hasattr(v, 'imc'):
        if hasattr(v.imc, 'implicit'):           
            pg0.append(v.imc.implicit)
        else:
            for iv in v.imc:
                pg0.append(iv.implicit)
    if hasattr(v, 'imb'):
        if hasattr(v.imb, 'implicit'):           
            pg0.append(v.imb.implicit)
        else:
            for iv in v.imb:
                pg0.append(iv.implicit)
    if hasattr(v, 'imo'):
        if hasattr(v.imo, 'implicit'):           
            pg0.append(v.imo.implicit)
        else:
            for iv in v.imo:
                pg0.append(iv.implicit)
    if hasattr(v, 'ia'):
        if hasattr(v.ia, 'implicit'):           
            pg0.append(v.ia.implicit)
        else:
            for iv in v.ia:
                pg0.append(iv.implicit)
    if hasattr(v, 'attn'):
        if hasattr(v.attn, 'logit_scale'):   
            pg0.append(v.attn.logit_scale)
        if hasattr(v.attn, 'q_bias'):   
            pg0.append(v.attn.q_bias)
        if hasattr(v.attn, 'v_bias'):  
            pg0.append(v.attn.v_bias)
        if hasattr(v.attn, 'relative_position_bias_table'):  
            pg0.append(v.attn.relative_position_bias_table)
    if hasattr(v, 'rbr_dense'):
        if hasattr(v.rbr_dense, 'weight_rbr_origin'):  
            pg0.append(v.rbr_dense.weight_rbr_origin)
        if hasattr(v.rbr_dense, 'weight_rbr_avg_conv'): 
            pg0.append(v.rbr_dense.weight_rbr_avg_conv)
        if hasattr(v.rbr_dense, 'weight_rbr_pfir_conv'):  
            pg0.append(v.rbr_dense.weight_rbr_pfir_conv)
        if hasattr(v.rbr_dense, 'weight_rbr_1x1_kxk_idconv1'): 
            pg0.append(v.rbr_dense.weight_rbr_1x1_kxk_idconv1)
        if hasattr(v.rbr_dense, 'weight_rbr_1x1_kxk_conv2'):   
            pg0.append(v.rbr_dense.weight_rbr_1x1_kxk_conv2)
        if hasattr(v.rbr_dense, 'weight_rbr_gconv_dw'):   
            pg0.append(v.rbr_dense.weight_rbr_gconv_dw)
        if hasattr(v.rbr_dense, 'weight_rbr_gconv_pw'):   
            pg0.append(v.rbr_dense.weight_rbr_gconv_pw)
        if hasattr(v.rbr_dense, 'vector'):   
            pg0.append(v.rbr_dense.vector)

if opt.adam:
    optimizer = optim.Adam(pg0, lr=hyp['lr0'], betas=(hyp['momentum'], 0.999))  # adjust beta1 to momentum
else:
    optimizer = optim.SGD(pg0, lr=hyp['lr0'], momentum=hyp['momentum'], nesterov=True)

optimizer.add_param_group({'params': pg1, 'weight_decay': hyp['weight_decay']})  # add pg1 with weight_decay
optimizer.add_param_group({'params': pg2})  # add pg2 (biases)
logger.info('Optimizer groups: %g .bias, %g conv.weight, %g other' % (len(pg2), len(pg1), len(pg0)))
del pg0, pg1, pg2

# Scheduler https://arxiv.org/pdf/1812.01187.pdf
# https://pytorch.org/docs/stable/_modules/torch/optim/lr_scheduler.html#OneCycleLR
if opt.linear_lr:
    lf = lambda x: (1 - x / (epochs - 1)) * (1.0 - hyp['lrf']) + hyp['lrf']  # linear
else:
    lf = one_cycle(1, hyp['lrf'], epochs)  # cosine 1->hyp['lrf']
scheduler = lr_scheduler.LambdaLR(optimizer, lr_lambda=lf)
# plot_lr_scheduler(optimizer, scheduler, epochs)

Scaled weight_decay = 0.0005
Optimizer groups: 115 .bias, 115 conv.weight, 115 other


In [15]:
# EMA
ema = ModelEMA(model) if rank in [-1, 0] else None

# Resume
start_epoch, best_fitness = 0, 0.0
if pretrained:
    # Optimizer
    if ckpt['optimizer'] is not None:
        optimizer.load_state_dict(ckpt['optimizer'])
        best_fitness = ckpt['best_fitness']

    # EMA
    if ema and ckpt.get('ema'):
        ema.ema.load_state_dict(ckpt['ema'].float().state_dict())
        ema.updates = ckpt['updates']

    # Results
    if ckpt.get('training_results') is not None:
        results_file.write_text(ckpt['training_results'])  # write results.txt

    # Epochs
    start_epoch = ckpt['epoch'] + 1
    if opt.resume:
        assert start_epoch > 0, '%s training to %g epochs is finished, nothing to resume.' % (weights, epochs)
    if epochs < start_epoch:
        logger.info('%s has been trained for %g epochs. Fine-tuning for %g additional epochs.' %
                    (weights, ckpt['epoch'], epochs))
        epochs += ckpt['epoch']  # finetune additional epochs

    del ckpt, state_dict

last.pt has been trained for 29 epochs. Fine-tuning for 10 additional epochs.


In [16]:
# Image sizes
gs = max(int(model.stride.max()), 32)  # grid size (max stride)
nl = model.model[-1].nl  # number of detection layers (used for scaling hyp['obj'])
imgsz, imgsz_test = [check_img_size(x, gs) for x in opt.img_size]  # verify imgsz are gs-multiples

In [17]:
nl

4

In [18]:
# DP mode
if cuda and rank == -1 and torch.cuda.device_count() > 1:
    model = torch.nn.DataParallel(model)

# SyncBatchNorm
if opt.sync_bn and cuda and rank != -1:
    model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model).to(device)
    logger.info('Using SyncBatchNorm()')


# Load Dataloader

In [21]:
# Trainloader
dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt,
                                        hyp=hyp, augment=False, cache=opt.cache_images, rect=opt.rect, rank=rank,
                                        world_size=opt.world_size, workers=opt.workers,
                                        image_weights=opt.image_weights, quad=opt.quad, prefix=colorstr('train: '))
mlc = np.concatenate(dataset.labels, 0)[:, 0].max()  # max label class
nb = len(dataloader)  # number of batches
assert mlc < nc, 'Label class %g exceeds nc=%g in %s. Possible class labels are 0-%g' % (mlc, nc, opt.data, nc - 1)

train: Scanning 'custom_data/labels/train.cache' images and labels... 14 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 14/14 [00:00<?, ?it/s]


In [22]:
rank

-1

In [19]:
# Process 0
# if rank in [-1, 0]:
#     testloader = create_dataloader(test_path, imgsz_test, batch_size * 2, gs, opt,  # testloader
#                                     hyp=hyp, cache=opt.cache_images and not opt.notest, rect=True, rank=-1,
#                                     world_size=opt.world_size, workers=opt.workers,
#                                     pad=0.5, prefix=colorstr('val: '))[0]

#     if not opt.resume:
#         labels = np.concatenate(dataset.labels, 0)
#         c = torch.tensor(labels[:, 0])  # classes
#         # cf = torch.bincount(c.long(), minlength=nc) + 1.  # frequency
#         # model._initialize_biases(cf.to(device))
#         if plots:
#             #plot_labels(labels, names, save_dir, loggers)
#             if tb_writer:
#                 tb_writer.add_histogram('classes', c, 0)

#         # Anchors
#         if not opt.noautoanchor:
#             check_anchors(dataset, model=model, thr=hyp['anchor_t'], imgsz=imgsz)
#         model.half().float()  # pre-reduce anchor precision

model.half().float()  # pre-reduce anchor precision

Model(
  (model): Sequential(
    (0): ReOrg()
    (1): Conv(
      (conv): Conv2d(12, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU()
    )
    (2): Conv(
      (conv): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU()
    )
    (3): Conv(
      (conv): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU()
    )
    (4): Conv(
      (conv): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU()
    )
    (5): Conv(
      (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1)

In [20]:
# DDP mode
if cuda and rank != -1:
    model = DDP(model, device_ids=[opt.local_rank], output_device=opt.local_rank,
                # nn.MultiheadAttention incompatibility with DDP https://github.com/pytorch/pytorch/issues/26698
                find_unused_parameters=any(isinstance(layer, nn.MultiheadAttention) for layer in model.modules()))

In [21]:
# Model parameters
hyp['box'] *= 3. / nl  # scale to layers
hyp['cls'] *= nc / 80. * 3. / nl  # scale to classes and layers
hyp['obj'] *= (imgsz / 640) ** 2 * 3. / nl  # scale to image size and layers
hyp['label_smoothing'] = opt.label_smoothing
model.nc = nc  # attach number of classes to model
model.hyp = hyp  # attach hyperparameters to model
model.gr = 1.0  # iou loss ratio (obj_loss = 1.0 or iou)
model.class_weights = torch.tensor([1.25353, 0.31338, 1.25353, 1.25353, 0.62676, 1.25353, 0.62676, 1.25353, 1.25353, 1.25353, 0.15669, 1.25353, 1.25353, 1.25353, 1.25353, 1.25353, 1.25353, 1.25353, 1.25353, 0.62676, 1.25353, 1.25353, 1.25353, 0.08954, 0.41784, 1.25353, 1.25353, 1.25353, 0.62676, 1.25353, 1.25353, 0.12535, 0.25071, 0.10446,
        1.25353, 0.25071, 0.41784, 1.25353, 1.25353, 1.25353, 1.25353, 1.25353, 1.25353, 1.25353, 1.25353, 1.25353],device='cuda:0', dtype=torch.float64)  #labels_to_class_weights(dataset.labels, nc).to(device) * nc  # attach class weights
model.names = names

In [ ]:
# Start training
t0 = time.time()
nw = max(round(hyp['warmup_epochs'] * nb), 1000)  # number of warmup iterations, max(3 epochs, 1k iterations)
# nw = min(nw, (epochs - start_epoch) / 2 * nb)  # limit warmup to < 1/2 of training
maps = np.zeros(nc)  # mAP per class
results = (0, 0, 0, 0, 0, 0, 0)  # P, R, mAP@.5, mAP@.5-.95, val_loss(box, obj, cls)
scheduler.last_epoch = start_epoch - 1  # do not move
scaler = amp.GradScaler(enabled=cuda)
compute_loss_ota = ComputeLossAuxOTA(model)  # init loss class
compute_loss = ComputeLoss(model)  # init loss class
logger.info(f'Image sizes {imgsz} train, {imgsz_test} test\n'
            f'Using {dataloader.num_workers} dataloader workers\n'
            f'Logging results to {save_dir}\n'
            f'Starting training for {epochs} epochs...')

In [27]:
for epoch in range(start_epoch, epochs):  # epoch ------------------------------------------------------------------
    with torch.no_grad():
        model.train()
        print(epoch)
        # Update image weights (optional)
        if opt.image_weights:
            # Generate indices
            if rank in [-1, 0]:
                cw = model.class_weights.cpu().numpy() * (1 - maps) ** 2 / nc  # class weights
                iw = labels_to_image_weights(dataset.labels, nc=nc, class_weights=cw)  # image weights
                dataset.indices = random.choices(range(dataset.n), weights=iw, k=dataset.n)  # rand weighted idx
            # Broadcast if DDP
            if rank != -1:
                indices = (torch.tensor(dataset.indices) if rank == 0 else torch.zeros(dataset.n)).int()
                dist.broadcast(indices, 0)
                if rank != 0:
                    dataset.indices = indices.cpu().numpy()

        # Update mosaic border
        # b = int(random.uniform(0.25 * imgsz, 0.75 * imgsz + gs) // gs * gs)
        # dataset.mosaic_border = [b - imgsz, -b]  # height, width borders

        mloss = torch.zeros(4, device=device)  # mean losses
        if rank != -1:
            dataloader.sampler.set_epoch(epoch)
        pbar = enumerate(dataloader)
        logger.info(('\n' + '%10s' * 8) % ('Epoch', 'gpu_mem', 'box', 'obj', 'cls', 'total', 'labels', 'img_size'))
        if rank in [-1, 0]:
            pbar = tqdm(pbar, total=nb)  # progress bar
        optimizer.zero_grad()
        for i, (imgs, targets, paths, _) in pbar:  # batch -------------------------------------------------------------
            ni = i + nb * epoch  # number integrated batches (since train start)
            imgs = imgs.to(device, non_blocking=True).float() / 255.0  # uint8 to float32, 0-255 to 0.0-1.0

            # Warmup
            if ni <= nw:
                xi = [0, nw]  # x interp
                # model.gr = np.interp(ni, xi, [0.0, 1.0])  # iou loss ratio (obj_loss = 1.0 or iou)
                accumulate = max(1, np.interp(ni, xi, [1, nbs / total_batch_size]).round())
                for j, x in enumerate(optimizer.param_groups):
                    # bias lr falls from 0.1 to lr0, all other lrs rise from 0.0 to lr0
                    x['lr'] = np.interp(ni, xi, [hyp['warmup_bias_lr'] if j == 2 else 0.0, x['initial_lr'] * lf(epoch)])
                    if 'momentum' in x:
                        x['momentum'] = np.interp(ni, xi, [hyp['warmup_momentum'], hyp['momentum']])

            # Multi-scale
            if opt.multi_scale:
                sz = random.randrange(imgsz * 0.5, imgsz * 1.5 + gs) // gs * gs  # size
                sf = sz / max(imgs.shape[2:])  # scale factor
                if sf != 1:
                    ns = [math.ceil(x * sf / gs) * gs for x in imgs.shape[2:]]  # new shape (stretched to gs-multiple)
                    imgs = F.interpolate(imgs, size=ns, mode='bilinear', align_corners=False)
            print(imgs)
            print(targets)
            # Forward
            with amp.autocast(enabled=cuda):
                pred = model(imgs)  # forward
                # loss, loss_items = compute_loss_ota(pred, targets.to(device), imgs)
                print(pred)
                torch.save(pred,'predict_sample.pt')
                torch.save(targets, 'target_sample.pt')
                torch.save(imgs, 'imgs_sample.pt')
            break
        break


     Epoch   gpu_mem       box       obj       cls     total    labels  img_size


30


  0%|          | 0/14 [00:00<?, ?it/s]

tensor([[[[0.44706, 0.44706, 0.44706,  ..., 0.44706, 0.44706, 0.44706],
          [0.44706, 0.44706, 0.44706,  ..., 0.44706, 0.44706, 0.44706],
          [0.44706, 0.44706, 0.44706,  ..., 0.44706, 0.44706, 0.44706],
          ...,
          [0.44706, 0.44706, 0.44706,  ..., 0.44706, 0.44706, 0.44706],
          [0.44706, 0.44706, 0.44706,  ..., 0.44706, 0.44706, 0.44706],
          [0.44706, 0.44706, 0.44706,  ..., 0.44706, 0.44706, 0.44706]],

         [[0.44706, 0.44706, 0.44706,  ..., 0.44706, 0.44706, 0.44706],
          [0.44706, 0.44706, 0.44706,  ..., 0.44706, 0.44706, 0.44706],
          [0.44706, 0.44706, 0.44706,  ..., 0.44706, 0.44706, 0.44706],
          ...,
          [0.44706, 0.44706, 0.44706,  ..., 0.44706, 0.44706, 0.44706],
          [0.44706, 0.44706, 0.44706,  ..., 0.44706, 0.44706, 0.44706],
          [0.44706, 0.44706, 0.44706,  ..., 0.44706, 0.44706, 0.44706]],

         [[0.44706, 0.44706, 0.44706,  ..., 0.44706, 0.44706, 0.44706],
          [0.44706, 0.44706, 0

  0%|          | 0/14 [00:05<?, ?it/s]


# Explore loss function

In [22]:
pred = torch.load('predict_sample.pt')
targets = torch.load('target_sample.pt')
imgs = torch.load('imgs_sample.pt')

In [25]:
targets

tensor([[0.00000e+00, 1.00000e+01, 4.66309e-01, 6.19629e-01, 4.50195e-01, 7.02148e-01],
        [0.00000e+00, 3.60000e+01, 4.85840e-01, 3.74023e-01, 1.29883e-01, 3.90620e-02],
        [0.00000e+00, 3.30000e+01, 4.84863e-01, 2.81738e-01, 1.25977e-01, 2.63670e-02]])

## Build_targets function

### find_3_positive function

In [29]:
na = model.model[-1].na
na

3

In [30]:
nt = targets.shape[0]
nt

3

In [40]:
nl = model.model[-1].nl
nl

4

In [42]:
nc = model.model[-1].nc
nc

46

In [41]:
anchors = model.model[-1].anchors
anchors

tensor([[[ 2.37500,  3.37500],
         [ 5.50000,  5.00000],
         [ 4.75000, 11.75000]],

        [[ 6.00000,  4.25000],
         [ 5.37500,  9.50000],
         [11.25000,  8.56250]],

        [[ 4.37500,  9.40625],
         [ 9.46875,  8.25000],
         [ 7.43750, 16.93750]],

        [[ 6.81250,  9.60938],
         [11.54688,  5.93750],
         [14.45312, 12.37500]]], device='cuda:0')

In [43]:
stride = model.model[-1].stride
stride

tensor([ 8., 16., 32., 64.])

In [58]:
hyp = model.hyp

In [31]:
indices, anch = [], []

In [33]:
gain = torch.ones(7, device=targets.device).long()  # normalized to gridspace gain
gain

tensor([1, 1, 1, 1, 1, 1, 1])

In [34]:
ai = torch.arange(na, device=targets.device).float().view(na, 1).repeat(1, nt)  # same as .repeat_interleave(nt)
ai

tensor([[0., 0., 0.],
        [1., 1., 1.],
        [2., 2., 2.]])

In [35]:
targets = torch.cat((targets.repeat(na, 1, 1), ai[:, :, None]), 2)  # append anchor indices
targets

tensor([[[0.00000e+00, 1.00000e+01, 4.66309e-01, 6.19629e-01, 4.50195e-01, 7.02148e-01, 0.00000e+00],
         [0.00000e+00, 3.60000e+01, 4.85840e-01, 3.74023e-01, 1.29883e-01, 3.90620e-02, 0.00000e+00],
         [0.00000e+00, 3.30000e+01, 4.84863e-01, 2.81738e-01, 1.25977e-01, 2.63670e-02, 0.00000e+00]],

        [[0.00000e+00, 1.00000e+01, 4.66309e-01, 6.19629e-01, 4.50195e-01, 7.02148e-01, 1.00000e+00],
         [0.00000e+00, 3.60000e+01, 4.85840e-01, 3.74023e-01, 1.29883e-01, 3.90620e-02, 1.00000e+00],
         [0.00000e+00, 3.30000e+01, 4.84863e-01, 2.81738e-01, 1.25977e-01, 2.63670e-02, 1.00000e+00]],

        [[0.00000e+00, 1.00000e+01, 4.66309e-01, 6.19629e-01, 4.50195e-01, 7.02148e-01, 2.00000e+00],
         [0.00000e+00, 3.60000e+01, 4.85840e-01, 3.74023e-01, 1.29883e-01, 3.90620e-02, 2.00000e+00],
         [0.00000e+00, 3.30000e+01, 4.84863e-01, 2.81738e-01, 1.25977e-01, 2.63670e-02, 2.00000e+00]]])

In [36]:
g = 0.5  # bias

In [38]:
off = torch.tensor([[0, 0],
                            [1, 0], [0, 1], [-1, 0], [0, -1],  # j,k,l,m
                            # [1, 1], [1, -1], [-1, 1], [-1, -1],  # jk,jm,lk,lm
                            ], device=targets.device).float() * g  # offsets
off

tensor([[ 0.00000,  0.00000],
        [ 0.50000,  0.00000],
        [ 0.00000,  0.50000],
        [-0.50000,  0.00000],
        [ 0.00000, -0.50000]])

In [44]:
for i in [0]: #range(nl):
    anchors_s = anchors[i]
    gain[2:6] = torch.tensor(pred[i].shape)[[3, 2, 3, 2]]  # xyxy gain


In [46]:
anchors_s

tensor([[ 2.37500,  3.37500],
        [ 5.50000,  5.00000],
        [ 4.75000, 11.75000]], device='cuda:0')

In [47]:
gain

tensor([  1,   1, 160, 160, 160, 160,   1])

In [53]:
t = targets * gain
t = t.to(device='cuda')
t

tensor([[[  0.00000,  10.00000,  74.60941,  99.14064,  72.03123, 112.34368,   0.00000],
         [  0.00000,  36.00000,  77.73433,  59.84368,  20.78123,   6.24992,   0.00000],
         [  0.00000,  33.00000,  77.57814,  45.07808,  20.15626,   4.21872,   0.00000]],

        [[  0.00000,  10.00000,  74.60941,  99.14064,  72.03123, 112.34368,   1.00000],
         [  0.00000,  36.00000,  77.73433,  59.84368,  20.78123,   6.24992,   1.00000],
         [  0.00000,  33.00000,  77.57814,  45.07808,  20.15626,   4.21872,   1.00000]],

        [[  0.00000,  10.00000,  74.60941,  99.14064,  72.03123, 112.34368,   2.00000],
         [  0.00000,  36.00000,  77.73433,  59.84368,  20.78123,   6.24992,   2.00000],
         [  0.00000,  33.00000,  77.57814,  45.07808,  20.15626,   4.21872,   2.00000]]], device='cuda:0')

In [54]:
r = t[:, :, 4:6] / anchors_s[:, None]  # wh ratio
r

tensor([[[30.32894, 33.28702],
         [ 8.74999,  1.85183],
         [ 8.48685,  1.24999]],

        [[13.09659, 22.46874],
         [ 3.77840,  1.24998],
         [ 3.66477,  0.84374]],

        [[15.16447,  9.56116],
         [ 4.37500,  0.53191],
         [ 4.24342,  0.35904]]], device='cuda:0')

In [60]:
j = torch.max(r, 1. / r).max(2)[0] < hyp['anchor_t']
j

tensor([[False, False, False],
        [False,  True,  True],
        [False, False, False]], device='cuda:0')

In [63]:
t = t[j]
t

tensor([[ 0.00000, 36.00000, 77.73433, 59.84368, 20.78123,  6.24992,  1.00000],
        [ 0.00000, 33.00000, 77.57814, 45.07808, 20.15626,  4.21872,  1.00000]], device='cuda:0')

In [65]:
gxy = t[:, 2:4]
gxy

tensor([[77.73433, 59.84368],
        [77.57814, 45.07808]], device='cuda:0')

In [70]:
gain = gain.to('cuda')


In [71]:
gxi = gain[[2, 3]] - gxy  # inverse
gxi

tensor([[ 82.26567, 100.15633],
        [ 82.42186, 114.92192]], device='cuda:0')

In [72]:
j, k = ((gxy % 1. < g) & (gxy > 1.)).T
j, k

(tensor([False, False], device='cuda:0'),
 tensor([False,  True], device='cuda:0'))

In [73]:
l, m = ((gxi % 1. < g) & (gxi > 1.)).T
l, m

(tensor([True, True], device='cuda:0'),
 tensor([ True, False], device='cuda:0'))

In [74]:
j = torch.stack((torch.ones_like(j), j, k, l, m))
j

tensor([[ True,  True],
        [False, False],
        [False,  True],
        [ True,  True],
        [ True, False]], device='cuda:0')

In [75]:
t = t.repeat((5, 1, 1))[j]
t

tensor([[ 0.00000, 36.00000, 77.73433, 59.84368, 20.78123,  6.24992,  1.00000],
        [ 0.00000, 33.00000, 77.57814, 45.07808, 20.15626,  4.21872,  1.00000],
        [ 0.00000, 33.00000, 77.57814, 45.07808, 20.15626,  4.21872,  1.00000],
        [ 0.00000, 36.00000, 77.73433, 59.84368, 20.78123,  6.24992,  1.00000],
        [ 0.00000, 33.00000, 77.57814, 45.07808, 20.15626,  4.21872,  1.00000],
        [ 0.00000, 36.00000, 77.73433, 59.84368, 20.78123,  6.24992,  1.00000]], device='cuda:0')

In [78]:
off = off.to('cuda')

In [79]:
offsets = (torch.zeros_like(gxy)[None] + off[:, None])[j]
offsets

tensor([[ 0.00000,  0.00000],
        [ 0.00000,  0.00000],
        [ 0.00000,  0.50000],
        [-0.50000,  0.00000],
        [-0.50000,  0.00000],
        [ 0.00000, -0.50000]], device='cuda:0')

In [80]:
b, c = t[:, :2].long().T # image, class
b, c

(tensor([0, 0, 0, 0, 0, 0], device='cuda:0'),
 tensor([36, 33, 33, 36, 33, 36], device='cuda:0'))

In [81]:
t

tensor([[ 0.00000, 36.00000, 77.73433, 59.84368, 20.78123,  6.24992,  1.00000],
        [ 0.00000, 33.00000, 77.57814, 45.07808, 20.15626,  4.21872,  1.00000],
        [ 0.00000, 33.00000, 77.57814, 45.07808, 20.15626,  4.21872,  1.00000],
        [ 0.00000, 36.00000, 77.73433, 59.84368, 20.78123,  6.24992,  1.00000],
        [ 0.00000, 33.00000, 77.57814, 45.07808, 20.15626,  4.21872,  1.00000],
        [ 0.00000, 36.00000, 77.73433, 59.84368, 20.78123,  6.24992,  1.00000]], device='cuda:0')

In [82]:
gxy = t[:, 2:4]  # grid xy
gxy

tensor([[77.73433, 59.84368],
        [77.57814, 45.07808],
        [77.57814, 45.07808],
        [77.73433, 59.84368],
        [77.57814, 45.07808],
        [77.73433, 59.84368]], device='cuda:0')

In [84]:
gwh = t[:, 4:6]  # grid wh
gwh

tensor([[20.78123,  6.24992],
        [20.15626,  4.21872],
        [20.15626,  4.21872],
        [20.78123,  6.24992],
        [20.15626,  4.21872],
        [20.78123,  6.24992]], device='cuda:0')

In [85]:
gij = (gxy - offsets).long()
gij

tensor([[77, 59],
        [77, 45],
        [77, 44],
        [78, 59],
        [78, 45],
        [77, 60]], device='cuda:0')

In [86]:
gi, gj = gij.T  # grid xy indices
gi, gj

(tensor([77, 77, 77, 78, 78, 77], device='cuda:0'),
 tensor([59, 45, 44, 59, 45, 60], device='cuda:0'))

In [87]:
a = t[:, 6].long()  # anchor indices
a

tensor([1, 1, 1, 1, 1, 1], device='cuda:0')

In [88]:
indices.append((b, a, gj.clamp_(0, gain[3] - 1), gi.clamp_(0, gain[2] - 1)))  # image, anchor, grid indices
indices

[(tensor([0, 0, 0, 0, 0, 0], device='cuda:0'),
  tensor([1, 1, 1, 1, 1, 1], device='cuda:0'),
  tensor([59, 45, 44, 59, 45, 60], device='cuda:0'),
  tensor([77, 77, 77, 78, 78, 77], device='cuda:0'))]

In [89]:
gain[3] - 1

tensor(159, device='cuda:0')

In [90]:
anch.append(anchors[a])
anch

[tensor([[[ 6.00000,  4.25000],
          [ 5.37500,  9.50000],
          [11.25000,  8.56250]],
 
         [[ 6.00000,  4.25000],
          [ 5.37500,  9.50000],
          [11.25000,  8.56250]],
 
         [[ 6.00000,  4.25000],
          [ 5.37500,  9.50000],
          [11.25000,  8.56250]],
 
         [[ 6.00000,  4.25000],
          [ 5.37500,  9.50000],
          [11.25000,  8.56250]],
 
         [[ 6.00000,  4.25000],
          [ 5.37500,  9.50000],
          [11.25000,  8.56250]],
 
         [[ 6.00000,  4.25000],
          [ 5.37500,  9.50000],
          [11.25000,  8.56250]]], device='cuda:0')]

In [163]:
pred = torch.load('predict_sample.pt', 'cuda')
targets = torch.load('target_sample.pt', 'cuda')
imgs = torch.load('imgs_sample.pt', 'cuda')

In [164]:
compute_loss_ota = ComputeLossAuxOTA(model)

In [101]:
indices, anch = compute_loss_ota.find_3_positive(pred, targets)

In [104]:
len(pred)

8

In [106]:
pred[0].shape

torch.Size([1, 3, 160, 160, 51])

In [118]:
nl = len(pred)
nl

8

In [120]:
pred[0].shape[0]

1

In [125]:
batch_idx = 0
b_idx = targets[:, 0]==batch_idx
b_idx

tensor([True, True, True], device='cuda:0')

In [127]:
this_target = targets[b_idx]
this_target

tensor([[0.00000e+00, 1.00000e+01, 4.66309e-01, 6.19629e-01, 4.50195e-01, 7.02148e-01],
        [0.00000e+00, 3.60000e+01, 4.85840e-01, 3.74023e-01, 1.29883e-01, 3.90620e-02],
        [0.00000e+00, 3.30000e+01, 4.84863e-01, 2.81738e-01, 1.25977e-01, 2.63670e-02]], device='cuda:0')

In [129]:
txywh = this_target[:, 2:6] * imgs[batch_idx].shape[1]
txywh

tensor([[596.87524, 793.12512, 576.24988, 898.74945],
        [621.87463, 478.74942, 166.24982,  49.99939],
        [620.62512, 360.62463, 161.25006,  33.74979]], device='cuda:0')

In [134]:
from utils.general import *

In [136]:
txyxy = xywh2xyxy(txywh)
txyxy

tensor([[ 308.75031,  343.75040,  885.00018, 1242.49988],
        [ 538.74976,  453.74973,  704.99951,  503.74911],
        [ 540.00012,  343.74976,  701.25012,  377.49951]], device='cuda:0')

In [137]:
pxyxys = []
p_cls = []
p_obj = []
from_which_layer = []
all_b = []
all_a = []
all_gj = []
all_gi = []
all_anch = []

In [140]:
for i, pi in enumerate(pred):
    print(pi.shape)
    break

torch.Size([1, 3, 160, 160, 51])


In [142]:
i = 0
pi = pred[i]

In [144]:
b, a, gj, gi = indices[i]
b, a, gj, gi

(tensor([0, 0, 0, 0, 0, 0], device='cuda:0'),
 tensor([1, 1, 1, 1, 1, 1], device='cuda:0'),
 tensor([59, 45, 44, 59, 45, 60], device='cuda:0'),
 tensor([77, 77, 77, 78, 78, 77], device='cuda:0'))

In [145]:
idx = (b == batch_idx)
idx

tensor([True, True, True, True, True, True], device='cuda:0')

In [146]:
b, a, gj, gi = b[idx], a[idx], gj[idx], gi[idx]  
b, a, gj, gi

(tensor([0, 0, 0, 0, 0, 0], device='cuda:0'),
 tensor([1, 1, 1, 1, 1, 1], device='cuda:0'),
 tensor([59, 45, 44, 59, 45, 60], device='cuda:0'),
 tensor([77, 77, 77, 78, 78, 77], device='cuda:0'))

In [147]:
all_b.append(b)
all_a.append(a)
all_gj.append(gj)
all_gi.append(gi)
all_anch.append(anch[i][idx])
from_which_layer.append(torch.ones(size=(len(b),)) * i)

In [150]:
fg_pred = pi[b, a, gj, gi]
fg_pred

tensor([[  2.13761,   0.48973,   3.30853,   0.14891,  -0.70374, -13.76682, -10.64700,  -9.48356, -13.73276, -11.71780, -10.81005, -11.87727, -12.77069, -14.79456, -14.29358,  -7.89700, -10.37494, -11.92209, -12.99648, -15.10925, -10.00504, -13.05450, -12.55408, -14.82550,  -5.77114, -12.81433, -13.06496, -12.79646,
         -19.86053, -10.71533, -12.70239, -13.43266, -15.22316, -15.48718, -17.07745, -16.00653, -10.76097, -19.62309,  -7.16016,  -7.88379, -14.53186,  -5.66453,   4.06184,  -8.89586,  -6.97873, -10.39764,  -8.66766,  -8.36440, -11.70156,  -4.35818, -10.42244],
        [  0.49509,   0.92299,   3.24026,  -0.03214,   1.29311, -12.28018, -10.17651, -12.21355, -12.09506, -12.95349, -10.68085, -11.89508, -11.71753, -12.10306, -12.27209, -11.37167, -10.34070, -12.40659, -11.67981, -12.46490, -13.14636, -11.44711, -13.03693, -14.91957, -12.18048, -11.95442, -13.64162, -12.78745,
         -12.01630, -13.83476, -12.82288, -13.81770, -12.65999,  -9.60452, -12.46967, -12.83423,  -9.39

In [151]:
p_obj.append(fg_pred[:, 4:5])
p_obj

[tensor([[-0.70374],
         [ 1.29311],
         [-4.00689],
         [ 1.22274],
         [-0.49261],
         [-3.60664]], device='cuda:0')]

In [153]:
p_cls.append(fg_pred[:, 5:])
p_cls

[tensor([[-13.76682, -10.64700,  -9.48356, -13.73276, -11.71780, -10.81005, -11.87727, -12.77069, -14.79456, -14.29358,  -7.89700, -10.37494, -11.92209, -12.99648, -15.10925, -10.00504, -13.05450, -12.55408, -14.82550,  -5.77114, -12.81433, -13.06496, -12.79646, -19.86053, -10.71533, -12.70239, -13.43266, -15.22316,
          -15.48718, -17.07745, -16.00653, -10.76097, -19.62309,  -7.16016,  -7.88379, -14.53186,  -5.66453,   4.06184,  -8.89586,  -6.97873, -10.39764,  -8.66766,  -8.36440, -11.70156,  -4.35818, -10.42244],
         [-12.28018, -10.17651, -12.21355, -12.09506, -12.95349, -10.68085, -11.89508, -11.71753, -12.10306, -12.27209, -11.37167, -10.34070, -12.40659, -11.67981, -12.46490, -13.14636, -11.44711, -13.03693, -14.91957, -12.18048, -11.95442, -13.64162, -12.78745, -12.01630, -13.83476, -12.82288, -13.81770, -12.65999,
           -9.60452, -12.46967, -12.83423,  -9.39584, -14.27989,   9.00613, -13.65976, -12.85034,  -9.95847,  -9.39169, -10.92773, -10.56569, -11.75018, -1

In [155]:
p_cls[0].shape

torch.Size([6, 46])

In [156]:
grid = torch.stack([gi, gj], dim=1)
grid

tensor([[77, 59],
        [77, 45],
        [77, 44],
        [78, 59],
        [78, 45],
        [77, 60]], device='cuda:0')

In [158]:
pxy = (fg_pred[:, :2].sigmoid() * 2. - 0.5 + grid) * stride[i] #/ 8.
pxy

tensor([[626.31207, 477.92068],
        [621.94086, 367.45044],
        [621.51178, 363.37109],
        [626.82739, 477.87732],
        [622.11798, 366.91583],
        [624.93396, 478.88516]], device='cuda:0')

In [160]:
pwh = (fg_pred[:, 2:4].sigmoid() * 2) ** 2 * anch[i][idx] * stride[i] #/ 8.
pwh

tensor([[163.80058,  46.16613],
        [162.98708,  38.72464],
        [163.50804,  36.29567],
        [167.05859,  46.31744],
        [161.76233,  38.92634],
        [164.36638,  46.50768]], device='cuda:0')

In [161]:
pxywh = torch.cat([pxy, pwh], dim=-1)
pxyxy = xywh2xyxy(pxywh)
pxyxys.append(pxyxy)

pxyxys

[tensor([[544.41180, 454.83762, 708.21234, 501.00375],
         [540.44733, 348.08810, 703.43439, 386.81277],
         [539.75775, 345.22327, 703.26581, 381.51892],
         [543.29810, 454.71860, 710.35669, 501.03604],
         [541.23682, 347.45267, 702.99915, 386.37900],
         [542.75079, 455.63132, 707.11713, 502.13901]], device='cuda:0')]

In [166]:
compute_loss_ota.build_targets(pred[:4], targets, imgs)

([tensor([0, 0, 0, 0], device='cuda:0'),
  tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0'),
  tensor([0, 0, 0, 0, 0, 0], device='cuda:0'),
  tensor([0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')],
 [tensor([1, 1, 1, 1], device='cuda:0'),
  tensor([0, 0, 1, 2, 0, 1, 0, 0, 1, 2], device='cuda:0'),
  tensor([1, 2, 1, 2, 1, 2], device='cuda:0'),
  tensor([0, 1, 2, 0, 1, 2, 0, 1], device='cuda:0')],
 [tensor([59, 45, 59, 60], device='cuda:0'),
  tensor([29, 22, 29, 29, 22, 29, 30, 23, 30, 30], device='cuda:0'),
  tensor([24, 24, 24, 24, 25, 25], device='cuda:0'),
  tensor([12, 12, 12, 12, 12, 12, 11, 11], device='cuda:0')],
 [tensor([77, 77, 78, 77], device='cuda:0'),
  tensor([38, 38, 38, 38, 39, 39, 38, 38, 38, 38], device='cuda:0'),
  tensor([18, 18, 19, 19, 18, 18], device='cuda:0'),
  tensor([9, 9, 9, 8, 8, 8, 9, 9], device='cuda:0')],
 [tensor([[0.00000e+00, 3.60000e+01, 4.85840e-01, 3.74023e-01, 1.29883e-01, 3.90620e-02],
          [0.00000e+00, 3.30000e+01, 4.84863e-01, 2.81738e

In [167]:
model.gr

1.0